require "rscramblesolver/version"

require "rscramblesolver/dictionary/trie"
require "rscramblesolver/dictionary/simple_dictionary"
require "rscramblesolver/dictionary/word_reader"
require "rscramblesolver/search"
require "rscramblesolver/boardcreator"
require "rscramblesolver/board"
require "rscramblesolver/coordinates"
require "rscramblesolver/tileattributes"
require "rscramblesolver/tile"
require "rscramblesolver/tilecontainer"
require "rscramblesolver/searchresults"
